### ISSUE TITLE
Deploy your app in heroku and share the link in the main README

### ISSUE THREAD

**Issue by indikman** [YasinduWishmith/FoodApp#1]

**Comment by YasinduWishmith** [comment]
Aiya,
     I am still developing the web application.. At the beginning, i have
added you as a collaborater. I have noticed deadline is 20th December. So i
will deploy the application in heroku and send you the link before that
day.. Thank you..

**Comment by YasinduWishmith** [comment]
aiya,
    I have completed my food application project.
   Link :- https://food-app-evaluation.herokuapp.com/
