### ISSUE TITLE
Fix Stylesheet Issues

### ISSUE THREAD

**Issue by indikman** [YasinduWishmith/FoodApp#2]
There seems to be a lot of styling issues in the system. Please Clear them our before the evaluation tomorrow.

**Comment by YasinduWishmith** [comment]
aiya,
      i fixed some styling issues and deployed at heroku. but aiya there is
some problem of Rxjs(observable) in building. I have used it in blur
effect. however it works properly in localhost. i have tried so many ways
to fix it. but i could not fix it.

before Link:-  https://food-app-evaluation.herokuapp.com/
after Link:- https://my-food-app-yasindu.herokuapp.com/

**Comment by YasinduWishmith** [comment]
VID_20191219_024600.avi
<https://drive.google.com/file/d/1V0E7K-3oYEuA3az4vVx6gLWXVjxs_QoQ/view?usp=drive_web>
Aiya,

Unfortunately On the way i fixed the problem, my repo was collapsed. So i
make new repo and add you as a collaborater. I attached a video link for
local host running application..

**Comment by indikman** [comment]
This is fine. Appreciate the effort.

**Comment by YasinduWishmith** [comment]
Thank you for your kindly response aiya..

**Comment by YasinduWishmith** [comment]
Aiya,

   I resolved the RxJS(Observable) problem. Now properly work the link.
https://my-food-app-yasindu.herokuapp.com/

**Comment by indikman** [comment]
Good effort. You'll get a call from Arimac for internship confirmation. Good Luck

**Comment by YasinduWishmith** [comment]
Thank you for your kindly response aiya..
